server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/old_classmate
    password: p
    username: postgres

    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 12
      connection-timeout: 30000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.leoli.old_classmate.dao.DO
  configuration:
    map-underscore-to-camel-case: true

oc:
  config:
    search-type: elasticsearch